name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to dockerhub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASS }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sudheej/kubernetes-dashboard-proxy:latest
    - name: Push image
      run: docker push sudheej/kubernetes-dashboard-proxy:latest  
